### ISSUE TITLE
Official Home Assistant integration

### ISSUE THREAD

**Issue by klada** [easink/hass.aioheos.media_player#10]
It would be cool if this component could be part of the official HASS distribution.

Is there a particular reason why this component has not been sent upstream yet?

**Comment by fowlie** [comment]
👍

**Comment by skynet01** [comment]
Agreed, there are so many HEOS devices, i think it’s second popular after Sonos

**Comment by easink** [comment]
Follow this https://github.com/home-assistant/home-assistant/pull/21721/

closing
