### ISSUE TITLE
Installation on HASS.IO

### ISSUE THREAD

**Issue by zenturacp** [easink/hass.aioheos.media_player#5]
Hi - i  have problems installing this on HASS.IO

I have created the custom_components\media_player\heos.py and no matter what when i add it it says component not found.

Am i missing something essential here?

**Comment by netruner** [comment]
I have this same problem

**Comment by easink** [comment]
never used HASS.IO, cant help you here.

**Comment by zenturacp** [comment]
Okay but what logs or details can i provide to help trouble shoot it?

Im not that new to HASS but still - all other custom modules have just worked :-)

Can you point me in some direction? As i have understood HASS.IO is just a "supervisor" maintaining the HASS docker image .. 

So it should be more less the same as just installed native.. 

I have access to the docker image with home assistant - @easink do you know a logfile etc i could look in?

**Comment by zenturacp** [comment]
I have the file placed here

/config/custom_components/media_player
➜  media_player ls
heos.py
➜  media_player

**Comment by netruner** [comment]
I use normal compilation in debian. 
My file is in:

```
root@ha:~/.homeassistant/custom_components/media_player#
-rwxr-xr-x 1 root root 6097 gru 16 21:07 heos.py
```

in log 
`
[homeassistant.components.discovery] Unknown service discovered: DLNA {'host': '192.168.192.55', 'model_number': 'DWS-3000 3.0', 'name': 'Livingroom', 'serial': '0000001', 'ssdp_description': 'http://192.168.192.55:60006/', 'udn': 'uuid:6feaba2d-6f40-18ee-010a-183bdb50ea87', 'port': 60006, 'manufacturer': 'Denon', 'model_name': 'HEOS 3'}
`
in configuration.yaml

```
media_player:
   platform: heos
   host: 192.168.192.55
   name: heos_livingroom
```

**Comment by netruner** [comment]
I do not know what I did, but now working.
I see on UI what to play and volume setting working.
Not working text to speech.

```
kwi 19 19:14:30 ha hass[10830]: 2018-04-19 19:14:30 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: service_data=message=Test, entity_id=media_player.heos_livingroom, domain=tts, service_call_id=139664508190904-112, service=google_say>
kwi 19 19:14:31 ha hass[10830]: 2018-04-19 19:14:31 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: service_data=media_content_type=music, media_content_id=http://192.168.192.10:8123/api/tts_proxy/640ab2bae07bedc4c163f679a746f7ab7fb5d1fa_en_-_google.mp3, entity_id=['media_player.heos_livingroom'], domain=media_player, service_call_id=139664508190904-113, service=play_media>
kwi 19 19:14:31 ha hass[10830]: 2018-04-19 19:14:31 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall media_player.play_media: media_content_type=music, media_content_id=http://192.168.192.10:8123/api/tts_proxy/640ab2bae07bedc4c163f679a746f7ab7fb5d1fa_en_-_google.mp3, entity_id=['media_player.heos_livingroom']>
kwi 19 19:14:31 ha hass[10830]: , timestamp=1524158071.0877783, message=Error executing service <ServiceCall media_player.play_media: media_content_type=music, media_content_id=http://192.168.192.10:8123/api/tts_proxy/640ab2bae07bedc4c163f679a746f7ab7fb5d1fa_en_-_google.mp3, entity_id=['media_player.heos_livingroom']>>
```

script play from tune in not working

```
 testplay:
    sequence:
      - service: media_player.play_media
        entity_id: media_player.heos_livingroom
        data_template:
          media_content_id: http://n-6-1.dcs.redcdn.pl/sc/o2/Eurozet/live/chillizet.livx?audio=5
          media_content_type: music
```

```
kwi 19 19:16:12 ha hass[10830]: 2018-04-19 19:16:12 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: service_data=media_content_type=music, media_content_id=http://n-6-1.dcs.redcdn.pl/sc/o2/Eurozet/live/chillizet.livx?audio=5, entity_id=['media_player.heos_livingroom'], domain=media_player, service_call_id=139664508190904-116, service=play_media>
kwi 19 19:16:12 ha hass[10830]: 2018-04-19 19:16:12 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall media_player.play_media: media_content_type=music, media_content_id=http://n-6-1.dcs.redcdn.pl/sc/o2/Eurozet/live/chillizet.livx?audio=5, entity_id=['media_player.heos_livingroom']>
kwi 19 19:16:12 ha hass[10830]: , timestamp=1524158172.0677526, message=Error executing service <ServiceCall media_player.play_media: media_content_type=music, media_content_id=http://n-6-1.dcs.redcdn.pl/sc/o2/Eurozet/live/chillizet.livx?audio=5, entity_id=['media_player.heos_livingroom']>>
```

**Comment by easink** [comment]
nice, its working, sort of.... sometimes its a problem for HA to download the requirements for heos. You could try install the requirements manually if you cant get it to work.

**Comment by zenturacp** [comment]
Now it works - as you said @easink - sometimes it aparantly does not download and install the requirements - but now it works after 1. restart - wait 20 min restart again.

Closing the issue..
